### ISSUE TITLE
Metadata Requirements for the Variable Report

### ISSUE THREAD

**Issue by Andy20** [dzhw/metadatamanagement-io#1]
**mandatory metadata for each variable**
- labels
- missings
- variablenames

**mandatory metadata for some kind of variables**
- variable description 
- generation rules
- filter rules

@anneweber please update the preceding list (if necessary) using the table with the metadata requirements. 

All dataset teams should copy the list and add it as a task list in a comment below to get an overview about the current status.  

The current version of the metadata table can be found [here](https://github.com/dzhw/metadatamanagement-io/blob/master/datasetreport/excel/Vorlage_Metadatensammlung.xlsx) .

**Comment by Andy20** [comment]
**_Done in the SB08-Dataset (update forthcoming)_**

**mandatory metadata for each variable**

- [ ] labels
- [ ] missings
- [ ] variablenames

**mandatory metadata for some kind of variables**

- [ ] variable description
- [ ] generation rules
- [ ] filter rules

**Comment by Andy20** [comment]
@dzhw/sowis **I need responses...** ![Call Me](https://cloud.githubusercontent.com/assets/17981185/15139217/0ce0df7c-1695-11e6-9e0b-d778a20cd8e5.JPG)

**Comment by UteH** [comment]
**_Done for the SE19-Dataset (update forthcoming)_**

**mandatory metadata for each variable**

- [ ] labels
- [ ] missings
- [ ] variablenames

**mandatory metadata for some kind of variables**

- [ ] variable description
- [ ] generation rules
- [ ] filter rules

**Comment by anfranken** [comment]
@Andy20 maybe it's better to structure this issue like the [input interfaces](https://github.com/dzhw/metadatamanagement/wiki/Interfaces). For example:
- DataSet Import.xlsx
 - dataSetId
 - description
- Variable.zip
 - variable.xlsx
   - generationDetails
   - filterDetails
 - varible.json

**Comment by Andy20** [comment]
This issue was just to be thought as an quick overview, nevertheless you're right, our categories should be based on the exisisting categorization. Me or @anneweber will commit an update soon.
