### ISSUE TITLE
Collect and document infomations which can be used for the fdz.DZHW documentation guidelines

### ISSUE THREAD

**Issue by Andy20** [dzhw/metadatamanagement-io#2]

**Comment by Andy20** [comment]
@UteH

**Comment by Andy20** [comment]
[Word-Doc for the guidelines](https://github.com/dzhw/metadatamanagement-io/blob/master/Dokumentationsstandards/Dokumentationsstandards%20des%20fdz.docx)

**Comment by anfranken** [comment]
The fdz.DZHW documentation guidlines will be collected in this [repository](https://github.com/dzhw/FDZ_Allgemein)
