### ISSUE TITLE
instruments.xlsx > title

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement-io#3]
Hi @Andy20,

noch eine Frage zu `instruments > instruments.xlsx > attachments`: Die Zweite Welle des PP2014 hat z.B. keinen Titel, da es eine Online-Erhebung ist (analog abs2009) - wie sollen wir hier vorgehen?
- den ersten anpassen (der im Dokument (attachment) nicht vorkommt)?
  - W1: "Karrieren Promovierter - Bundesweite Befragung zu den Promotionsbedingungen und zur beruflichen Entwicklung der Promovierten des Prüfungsjahres 2013/14" (laut FB) 
  - W2: "Karrieren Promovierter - zweite bundesweite Befragung zu den Promotionsbedingungen und zur beruflichen Entwicklung der Promovierten des Prüfungsjahres 2013/14"
- keinen Titel angeben, da dieser ja auch im Dokument (attachment) nicht vorkommt?

**Comment by Andy20** [comment]
Hi @UteH, 

da der Titel verpflichtend ist, muss er sowohl im attachement als auch im instruments sheet angegeben werden. Ich würde daher genauso vorgehen, wie Du oben vorgeschlagen hast: Titel des ersten Instruments ergänzt um "zweite". Wie gesagt, das müsste in beiden Excel-Sheets (instruments und attachments) angepasst werden.

**Comment by UteH** [comment]
habe ich entsprechend angepasst, danke für die schnelle Antwort!
@anneweber ggf auch für euch relevant 🤓
